# -*- coding: utf-8 -*-
"""ML lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wXEAQ7RMaW8JgO26xdxTRPLOxo-a2XJU
"""

import numpy as np
my_arr=np.empty((2,2),dtype=int)
print(my_arr)

np.empty((2,3,4))

import numpy as np
my_arr=np.zeros((2,2),dtype=int)
print(my_arr)

np.zeros(10)

import numpy as np
my_arr=np.ones((2,2),dtype=int)
print(my_arr)

np.ones(10)

import numpy as np
arr=np.arange(9).reshape(3,3)
print(arr)

#python numpy 1D array example
import numpy as np
arr=np.array([101,102,103,104,105])
print(arr)
print(type(arr))

#example for 1D array and its operations
data=np.array(([1.5,-0.1,3],[0,-3,6.5]))
print(data)
print(data*10)
print(data+data)

data.shape

data.dtype

data1=[6,7.5,8,0,1]
arr=np.array(data1)
arr

data2=[[1,3,4,6],[0,9,7,11]]
arr=np.array(data2)
print(arr)
print(arr.ndim)
print(arr.shape)

#creating boolean array
arr=[1,2,'hello',False]
b=np.array(arr,dtype=bool)
b

x=np.array([49,7,44,27,13,35,71])
y=np.where(x>30,1,x)
print(x)
print(y)

ar=np.array(([1,-2,-3],[-4,5,6],[-7,8,-9]))
c=np.where(ar<0,0,ar)
c

x=np.array([49,7,44,27,13,35,71])
y=np.extract(x>40,x)
print(x)
print(y)

array=np.arange(10)
out=np.where(array%2==1,-1,array)
print(array)
print(out.reshape(2,5))

c=np.where((array<5) & (array>7),1,array)
c

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.vstack((a,b))
c

np.concatenate((a,b),axis=0)

ar=np.array[[]]

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.intersect1d(a,b)
c

